(() => {
  // Google keeps changing the markup of Gemini, Flow, and AI Studio. This
  // adapter uses only rendered image data. Flow may additionally read the
  // text of one structurally-associated Prompt card after a local Reuse Prompt
  // anchor is confirmed. AI Studio may read only the nearest preceding user
  // prompt turn in the same chat session as the generated image. Neither path
  // scans the whole page, conversations outside that session, or editors.
  const SITE_BY_HOST = {
    "gemini.google.com": "gemini",
    "aistudio.google.com": "google-ai-studio",
    "labs.google": "flow",
  };
  const IMAGE_HOSTS = new Set([
    "lh3.googleusercontent.com",
    "lh4.googleusercontent.com",
    "lh5.googleusercontent.com",
    "lh6.googleusercontent.com",
    "storage.googleapis.com",
    "generativelanguage.googleapis.com",
    "*.googleusercontent.com",
  ]);
  const BLOCK_URL_HINTS = [
    "avatar", "profile", "favicon", "logo", "icon", "sprite", "emoji",
    "thumbnail", "googlelogo", "placehold", "material-symbol",
  ];
  const FLOW_PATH = /^\/(?:fx\/tools\/)?flow(?:\/|$)/;
  // Flow places a media grid and its Prompt card in the same generation row,
  // but that row is nested deeply beneath the individual image link. The
  // limit is deliberately just enough for that documented row boundary, not a
  // page-wide search. Long prompts are normal for Flow, so preserve one card
  // up to 20k characters rather than silently dropping it.
  const FLOW_PROMPT_MAX_CHARS = 20_000;
  const FLOW_PROMPT_MAX_ANCESTORS = 14;
  const FLOW_PROMPT_MAX_NODES = 96;
  const FLOW_PROMPT_ANCHOR = /reuse\s+prompt/i;
  const AI_STUDIO_PROMPT_MAX_CHARS = 20_000;
  // AI Studio renders Markdown with a deeply expanded Angular node tree. This
  // budget applies only inside the already-selected single user-prompt block.
  const AI_STUDIO_PROMPT_MAX_NODES = 12_000;
  const AI_STUDIO_MAX_PREVIOUS_TURNS = 16;
  const MIN_EDGE = 512;
  const MIN_VISIBLE_AREA = 96 * 96;
  const seen = new Set();
  let autoCapture = true;
  let scanTimer = null;
  let observer = null;

  function currentProvider() {
    const host = String(location.hostname || "").toLowerCase();
    const provider = SITE_BY_HOST[host];
    if (provider !== "flow") return provider || "";
    const path = String(location.pathname || "").toLowerCase();
    return FLOW_PATH.test(path) ? provider : "";
  }

  function extensionAlive() {
    try {
      return typeof chrome === "object" && Boolean(chrome?.runtime?.id);
    } catch {
      return false;
    }
  }

  function isAllowedImageHost(hostname) {
    const host = String(hostname || "").toLowerCase();
    if (IMAGE_HOSTS.has(host)) return true;
    return host.endsWith(".googleusercontent.com") || host.endsWith(".ggpht.com");
  }

  function isAllowedLocalImageUrl(url) {
    // Flow serves generated bytes from this exact same-origin endpoint. Keep
    // the allowlist narrow so ordinary page assets cannot be copied locally.
    return url.hostname === "labs.google"
      && url.pathname === "/fx/api/trpc/media.getMediaUrlRedirect";
  }

  function imageSource(value) {
    const src = String(value || "").trim();
    if (!src || src.startsWith("data:")) return null;
    if (src.startsWith("blob:")) {
      try {
        const url = new URL(src);
        // A blob handle is page-local. Do not read a handle carrying another
        // origin, even if a page happens to render it in an image element.
        // AI Studio is the only supported site currently observed to render
        // generated output as a blob; this host gate avoids broad blob capture.
        if (location.hostname !== "aistudio.google.com" || url.origin !== location.origin) return null;
        return { kind: "local", url: src };
      } catch {
        return null;
      }
    }
    try {
      const url = new URL(src, location.href);
      if (url.protocol !== "https:") return null;
      const lower = `${url.hostname}${url.pathname}`.toLowerCase();
      if (BLOCK_URL_HINTS.some((hint) => lower.includes(hint))) return null;
      if (url.origin === location.origin && isAllowedLocalImageUrl(url)) {
        return { kind: "local", url: url.href };
      }
      if (!isAllowedImageHost(url.hostname)) return null;
      return { kind: "remote", url: url.href };
    } catch {
      return null;
    }
  }

  function supportedImageUrl(value) {
    return imageSource(value)?.url || "";
  }

  function imageUrlFor(img) {
    return imageSource(img?.currentSrc || img?.src || "")?.url || "";
  }

  function imageSourceFor(img) {
    return imageSource(img?.currentSrc || img?.src || "");
  }

  function elementAttribute(node, name) {
    try {
      return String(node?.getAttribute?.(name) || "").trim();
    } catch {
      return "";
    }
  }

  function flowNodeChildren(node) {
    return Array.from(node?.children || []).filter((child) => child && child.nodeType === 1);
  }

  function flowNodeIsExcludedFromPromptText(node) {
    const tag = String(node?.tagName || "").toLowerCase();
    if (["button", "a", "input", "textarea", "select", "option", "script", "style"].includes(tag)) return true;
    if (elementAttribute(node, "contenteditable").toLowerCase() === "true") return true;
    if (elementAttribute(node, "aria-hidden").toLowerCase() === "true") return true;
    return false;
  }

  function flowNodeIsVisible(node) {
    if (!node || node.nodeType !== 1) return false;
    const style = typeof getComputedStyle === "function" ? getComputedStyle(node) : null;
    if (style && (style.display === "none" || style.visibility === "hidden" || Number(style.opacity) === 0)) return false;
    const rect = node.getBoundingClientRect?.();
    if (!rect) return true;
    if (rect.width < 1 || rect.height < 1) return false;
    if (typeof innerWidth === "number" && typeof innerHeight === "number"
      && (rect.bottom <= 0 || rect.right <= 0 || rect.top >= innerHeight || rect.left >= innerWidth)) return false;
    return true;
  }

  function nodeIsRendered(node) {
    if (!node || node.nodeType !== 1) return false;
    const style = typeof getComputedStyle === "function" ? getComputedStyle(node) : null;
    if (style && (style.display === "none" || style.visibility === "hidden" || Number(style.opacity) === 0)) return false;
    const rect = node.getBoundingClientRect?.();
    return !rect || (rect.width >= 1 && rect.height >= 1);
  }

  function flowTextFromNode(node, { includeControls = false, maxNodes = FLOW_PROMPT_MAX_NODES } = {}) {
    const parts = [];
    let visited = 0;
    function visit(current) {
      if (!current || visited >= maxNodes) return;
      visited += 1;
      if (current.nodeType === 3) {
        const value = String(current.nodeValue || "").replace(/\s+/g, " ").trim();
        if (value) parts.push(value);
        return;
      }
      if (current.nodeType !== 1) return;
      if (!includeControls && flowNodeIsExcludedFromPromptText(current)) return;
      for (const child of Array.from(current.childNodes || [])) visit(child);
    }
    visit(node);
    return parts.join(" ").replace(/\s+/g, " ").trim();
  }

  function flowReusePromptAnchorCount(node) {
    let visited = 0;
    let count = 0;
    const stack = [node];
    while (stack.length && visited < FLOW_PROMPT_MAX_NODES && count < 2) {
      const current = stack.shift();
      if (!current || current.nodeType !== 1) continue;
      visited += 1;
      const tag = String(current.tagName || "").toLowerCase();
      const role = elementAttribute(current, "role").toLowerCase();
      const label = [
        elementAttribute(current, "aria-label"),
        elementAttribute(current, "title"),
        elementAttribute(current, "data-tooltip"),
      ].join(" ").trim();
      const text = flowTextFromNode(current, { includeControls: true, maxNodes: 12 });
      const buttonLike = tag === "button" || tag === "a" || role === "button" || Boolean(label);
      if (buttonLike && FLOW_PROMPT_ANCHOR.test(`${label} ${text}`)) count += 1;
      for (const child of flowNodeChildren(current)) stack.push(child);
    }
    return count;
  }

  function flowHasReusePromptAnchor(node) {
    return flowReusePromptAnchorCount(node) === 1;
  }

  function flowPromptTextFromCard(card) {
    if (!flowNodeIsVisible(card)) return "";
    const raw = flowTextFromNode(card);
    if (!raw || raw.length > FLOW_PROMPT_MAX_CHARS || !/\bprompt\b/i.test(raw)) return "";
    const prompt = raw
      .replace(/^\s*prompt\s*:?\s*/i, "")
      .replace(/\s+prompt\s*:?\s*$/i, "")
      .trim();
    if (!prompt || /^reuse\s+prompt$/i.test(prompt) || prompt.length > FLOW_PROMPT_MAX_CHARS) return "";
    return prompt;
  }

  function flowNearbyPromptCard(image) {
    if (!image || !flowNodeIsVisible(image)) {
      console.log("[MOSA Flow] Image not visible or invalid");
      return "";
    }
    let node = image;
    let bestPrompt = "";
    let debugInfo = { depths: [], foundCards: 0, foundReuseAnchors: 0 };

    for (let depth = 0; node && depth < FLOW_PROMPT_MAX_ANCESTORS; depth += 1) {
      const parent = node.parentElement;
      if (!parent) break;
      const siblings = flowNodeChildren(parent);
      const promptCards = siblings
        .filter((candidate) => candidate !== node && flowNodeIsVisible(candidate))
        .map((candidate) => ({ candidate, prompt: flowPromptTextFromCard(candidate) }))
        .filter((entry) => entry.prompt);

      debugInfo.foundCards += promptCards.length;
      debugInfo.depths.push({ depth, cards: promptCards.length });

      // The sibling card itself holds the image's Reuse Prompt control. This
      // preserves a one-image-group association even when Flow wraps the
      // image grid and its Prompt card at different depths.
      const reusePromptCards = promptCards.filter((entry) => flowHasReusePromptAnchor(entry.candidate));
      debugInfo.foundReuseAnchors += reusePromptCards.length;

      if (reusePromptCards.length === 1) {
        console.log("[MOSA Flow] Found prompt with Reuse anchor at depth", depth, reusePromptCards[0].prompt.slice(0, 100));
        return reusePromptCards[0].prompt;
      }

      // Fallback: if we found prompt cards without Reuse anchor, remember the first one
      if (!bestPrompt && promptCards.length > 0) {
        bestPrompt = promptCards[0].prompt;
        console.log("[MOSA Flow] Found fallback prompt at depth", depth, bestPrompt.slice(0, 100));
      }
      node = parent;
    }

    console.log("[MOSA Flow] Prompt search complete:", {
      ...debugInfo,
      returnedFallback: !!bestPrompt,
      promptLength: bestPrompt.length
    });

    // Return the fallback prompt if no Reuse anchor was found
    return bestPrompt;
  }

  function flowVisiblePromptForImage(image) {
    if (currentProvider() !== "flow" || !isVisibleGeneratedImage(image)) return null;
    const prompt = flowNearbyPromptCard(image);
    return prompt ? {
      prompt,
      promptStatus: "provider-visible-prompt",
      promptSource: "flow-visible-prompt",
    } : null;
  }

  function ancestorWithTag(node, tagName) {
    const expected = String(tagName || "").toUpperCase();
    let current = node;
    while (current && current !== document.documentElement) {
      if (String(current.tagName || "").toUpperCase() === expected) return current;
      current = current.parentElement;
    }
    return null;
  }

  function directTurnContainer(turn, role) {
    return flowNodeChildren(turn).find((child) => child.classList?.contains("chat-turn-container")
      && child.classList?.contains(role)) || null;
  }

  function descendantsWithClass(root, className, maxNodes = 256) {
    const matches = [];
    const stack = flowNodeChildren(root);
    let visited = 0;
    while (stack.length && visited < maxNodes && matches.length < 2) {
      const current = stack.shift();
      if (!current || current.nodeType !== 1) continue;
      visited += 1;
      if (current.classList?.contains(className)) matches.push(current);
      for (const child of flowNodeChildren(current)) stack.push(child);
    }
    return matches;
  }

  function aiStudioPromptFromUserTurn(turn) {
    const userContainer = directTurnContainer(turn, "user");
    if (!userContainer || !nodeIsRendered(userContainer)) return "";
    const promptBlocks = descendantsWithClass(userContainer, "user-prompt-container");
    if (promptBlocks.length !== 1 || !nodeIsRendered(promptBlocks[0])) return "";
    const prompt = flowTextFromNode(promptBlocks[0], { maxNodes: AI_STUDIO_PROMPT_MAX_NODES });
    if (!prompt || prompt.length > AI_STUDIO_PROMPT_MAX_CHARS) return "";
    return prompt;
  }

  function aiStudioVisibleUserPromptForImage(image) {
    if (currentProvider() !== "google-ai-studio" || !isVisibleGeneratedImage(image)) return null;
    const imageTurn = ancestorWithTag(image, "ms-chat-turn");
    const sessionContent = imageTurn?.parentElement;
    if (!imageTurn || !sessionContent?.classList?.contains("chat-session-content")
      || !directTurnContainer(imageTurn, "model")) return null;
    let previous = imageTurn.previousElementSibling;
    for (let count = 0; previous && count < AI_STUDIO_MAX_PREVIOUS_TURNS; count += 1) {
      if (String(previous.tagName || "").toLowerCase() === "ms-chat-turn") {
        const prompt = aiStudioPromptFromUserTurn(previous);
        if (prompt) return {
          prompt,
          promptStatus: "provider-visible-prompt",
          promptSource: "google-ai-studio-visible-user-prompt",
        };
      }
      previous = previous.previousElementSibling;
    }
    return null;
  }

  function isVisibleGeneratedImage(img) {
    if (!(img instanceof HTMLImageElement) || !img.complete) return false;
    const width = Number(img.naturalWidth || img.width || 0);
    const height = Number(img.naturalHeight || img.height || 0);
    if (width < MIN_EDGE || height < MIN_EDGE) return false;
    const rect = img.getBoundingClientRect?.();
    if (!rect || rect.width < 1 || rect.height < 1) return false;
    if (rect.bottom <= 0 || rect.right <= 0 || rect.top >= innerHeight || rect.left >= innerWidth) return false;
    if (Math.max(0, Math.min(rect.right, innerWidth) - Math.max(rect.left, 0))
      * Math.max(0, Math.min(rect.bottom, innerHeight) - Math.max(rect.top, 0)) < MIN_VISIBLE_AREA) return false;
    const style = getComputedStyle(img);
    if (style.display === "none" || style.visibility === "hidden" || Number(style.opacity) === 0) return false;
    return Boolean(imageSourceFor(img));
  }

  function arrayBufferToBase64(buffer) {
    const bytes = new Uint8Array(buffer);
    let binary = "";
    const chunk = 0x8000;
    for (let i = 0; i < bytes.length; i += chunk) {
      binary += String.fromCharCode(...bytes.subarray(i, i + chunk));
    }
    return btoa(binary);
  }

  async function bytesFromVisibleImage(source, img) {
    // This check is intentionally repeated immediately before reading bytes:
    // same-origin/Blob URLs are only eligible while their image is rendered,
    // loaded, and dimension-qualified in the current viewport.
    if (source?.kind !== "local" || !isVisibleGeneratedImage(img)) {
      throw new Error("请选择支持站点中的可见生成图片。");
    }
    const response = await fetch(source.url, {
      credentials: "same-origin",
      cache: "no-cache",
    });
    if (!response.ok) throw new Error(`Image download failed (${response.status})`);
    const blob = await response.blob();
    if (!blob || blob.size < 100) throw new Error("Downloaded image empty/too small");
    return {
      mimeType: blob.type || mimeTypeForUrl(source.url),
      imageBase64: arrayBufferToBase64(await blob.arrayBuffer()),
    };
  }

  async function sendCapture(provider, source, img) {
    if (!extensionAlive()) return Promise.resolve({ ok: false, error: "MOSA extension is unavailable." });
    const payload = {
      provider,
      mimeType: mimeTypeForUrl(source.url),
      pageUrl: location.href,
      promptStatus: "not-available",
      promptSource: "provider-visible-image",
      capturedAt: new Date().toISOString(),
    };
    if (provider === "flow") {
      const flowPrompt = flowVisiblePromptForImage(img);
      if (flowPrompt) Object.assign(payload, flowPrompt);
    }
    if (provider === "google-ai-studio") {
      const aiStudioPrompt = aiStudioVisibleUserPromptForImage(img);
      if (aiStudioPrompt) Object.assign(payload, aiStudioPrompt);
    }
    if (source.kind === "local") {
      const bytes = await bytesFromVisibleImage(source, img);
      payload.mimeType = bytes.mimeType;
      payload.imageBase64 = bytes.imageBase64;
    } else {
      // Public Google CDN sources retain the existing background download path.
      payload.imageUrl = source.url;
    }
    return chrome.runtime.sendMessage({
      type: "mosa.ingest",
      payload,
    });
  }

  function mimeTypeForUrl(imageUrl) {
    const extension = imageUrl.match(/\.([a-z0-9]+)(?:$|[?#])/i)?.[1]?.toLowerCase();
    if (extension === "jpg" || extension === "jpeg") return "image/jpeg";
    if (extension === "webp") return "image/webp";
    if (extension === "gif") return "image/gif";
    return "image/png";
  }

  function scan() {
    const provider = currentProvider();
    if (!provider || !autoCapture) return;
    for (const img of document.images || []) {
      if (!isVisibleGeneratedImage(img)) continue;
      const source = imageSourceFor(img);
      if (!source || seen.has(source.url)) continue;
      seen.add(source.url);
      sendCapture(provider, source, img)
        .then((response) => {
          // Authentication, origin, or service failures must remain retryable.
          // The background returns them as { ok: false } rather than rejecting.
          if (!response?.ok) seen.delete(source.url);
        })
        .catch(() => seen.delete(source.url));
    }
  }

  function scheduleScan() {
    if (scanTimer) clearTimeout(scanTimer);
    scanTimer = setTimeout(scan, 300);
  }

  (chrome.runtime?.sendMessage?.({ type: "mosa.getSettings" }) || Promise.resolve()).then((response) => {
    if (response?.ok && response.settings) autoCapture = response.settings.autoCapture !== false;
    scheduleScan();
  }).catch(() => scheduleScan());

  chrome.storage?.onChanged?.addListener?.((changes, area) => {
    if (area !== "local") return;
    if (changes.autoCapture) autoCapture = changes.autoCapture.newValue !== false;
    if (!changes.autoCapture && !changes.mosaBaseUrl && !changes.mosaToken) return;
    // A corrected address or Token should immediately retry images that were
    // rejected under the previous settings without requiring new generation.
    seen.clear();
    scheduleScan();
  });

  chrome.runtime?.onMessage?.addListener?.((message, _sender, sendResponse) => {
    if (!message || !["mosa.capture.saveImage", "mosa.capture.saveImageWithPrompt"].includes(message.type)) return false;
    const provider = currentProvider();
    const source = imageSource(message.imageUrl);
    const image = source
      ? Array.from(document.images || []).find((candidate) => imageSourceFor(candidate)?.url === source.url)
      : null;
    if (!provider || !source || (source.kind === "local" && !isVisibleGeneratedImage(image))) {
      sendResponse({ ok: false, error: "请选择支持站点中的生成图片。" });
      return false;
    }
    sendCapture(provider, source, image)
      .then((response) => sendResponse(response || { ok: true }))
      .catch((error) => sendResponse({ ok: false, error: error instanceof Error ? error.message : String(error) }));
    return true;
  });

  observer = new MutationObserver(scheduleScan);
  if (document.documentElement) observer.observe(document.documentElement, {
    childList: true,
    subtree: true,
    attributes: true,
    attributeFilter: ["src", "srcset", "style", "class"],
  });
  scheduleScan();
})();
